// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pri.WebApi.DeSchakel.Core.Data;

#nullable disable

namespace Pri.WebApi.DeSchakel.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240816182311_Starting")]
    partial class Starting
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationUserEvent", b =>
                {
                    b.Property<string>("ActionUsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EventsId")
                        .HasColumnType("int");

                    b.HasKey("ActionUsersId", "EventsId");

                    b.HasIndex("EventsId");

                    b.ToTable("ApplicationUserEvent");

                    b.HasData(
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000004",
                            EventsId = 1
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000004",
                            EventsId = 2
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000003",
                            EventsId = 3
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000003",
                            EventsId = 4
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000002",
                            EventsId = 5
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000002",
                            EventsId = 6
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000003",
                            EventsId = 7
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000002",
                            EventsId = 8
                        },
                        new
                        {
                            ActionUsersId = "00000000-0000-0000-0000-000000000002",
                            EventsId = 9
                        });
                });

            modelBuilder.Entity("EventGenre", b =>
                {
                    b.Property<int>("EventsId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("EventsId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("EventGenre");

                    b.HasData(
                        new
                        {
                            EventsId = 1,
                            GenresId = 5
                        },
                        new
                        {
                            EventsId = 2,
                            GenresId = 5
                        },
                        new
                        {
                            EventsId = 3,
                            GenresId = 7
                        },
                        new
                        {
                            EventsId = 4,
                            GenresId = 6
                        },
                        new
                        {
                            EventsId = 5,
                            GenresId = 8
                        },
                        new
                        {
                            EventsId = 5,
                            GenresId = 4
                        },
                        new
                        {
                            EventsId = 6,
                            GenresId = 8
                        },
                        new
                        {
                            EventsId = 7,
                            GenresId = 5
                        },
                        new
                        {
                            EventsId = 8,
                            GenresId = 2
                        },
                        new
                        {
                            EventsId = 8,
                            GenresId = 3
                        },
                        new
                        {
                            EventsId = 9,
                            GenresId = 8
                        },
                        new
                        {
                            EventsId = 9,
                            GenresId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            ConcurrencyStamp = "df1a5969-0b38-42d1-8e85-6501e5135f02",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            ConcurrencyStamp = "895268fc-12e5-4e92-801e-6f75d6c1b6e1",
                            Name = "Programmator",
                            NormalizedName = "PROGRAMMATOR"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            ConcurrencyStamp = "aebce31d-3636-46d3-adaa-cd351cb617b5",
                            Name = "Onthaal",
                            NormalizedName = "ONTHAAL"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            ConcurrencyStamp = "ff4648ca-26f9-454e-b14a-c44c733c10b0",
                            Name = "Bezoeker",
                            NormalizedName = "BEZOEKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Name",
                            ClaimValue = "Geert Deloof",
                            UserId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "email",
                            ClaimValue = "admin@cc.be",
                            UserId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Name",
                            ClaimValue = "Maaike Tubex",
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "email",
                            ClaimValue = "maaike@cc.be",
                            UserId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Name",
                            ClaimValue = "Joost Van den Kerkhove",
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "email",
                            ClaimValue = "joost@cc.be",
                            UserId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Name",
                            ClaimValue = "Veerle Hollants",
                            UserId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "email",
                            ClaimValue = "veerle@cc.be",
                            UserId = "00000000-0000-0000-0000-000000000004"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Name",
                            ClaimValue = "Paulien Desmet",
                            UserId = "00000000-0000-0000-0000-000000000005"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "email",
                            ClaimValue = "paulien@cc.be",
                            UserId = "00000000-0000-0000-0000-000000000005"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Name",
                            ClaimValue = "Filiep Verhelst",
                            UserId = "00000000-0000-0000-0000-000000000006"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "email",
                            ClaimValue = "f.v@telenet.be",
                            UserId = "00000000-0000-0000-0000-000000000006"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "registration-date",
                            ClaimValue = "2018-12-15",
                            UserId = "00000000-0000-0000-0000-000000000006"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "zipcode",
                            ClaimValue = "8793",
                            UserId = "00000000-0000-0000-0000-000000000006"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000001",
                            RoleId = "00000000-0000-0000-0000-000000000001"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000002",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000003",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000004",
                            RoleId = "00000000-0000-0000-0000-000000000002"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000005",
                            RoleId = "00000000-0000-0000-0000-000000000003"
                        },
                        new
                        {
                            UserId = "00000000-0000-0000-0000-000000000006",
                            RoleId = "00000000-0000-0000-0000-000000000004"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Zipcode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000001",
                            AccessFailedCount = 0,
                            City = "Beveren-Leie",
                            ConcurrencyStamp = "c8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cc.be",
                            EmailConfirmed = true,
                            Firstname = "Geert",
                            Lastname = "Deloof",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@CC.BE",
                            NormalizedUserName = "ADMIN@CC.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAECEBykEfUx2QNuKIOW+J4TAPWvGhMR54IUN0zRR+JA5lF5yX3Jno61GQIs39bQLDgQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "VVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "admin@cc.be",
                            Zipcode = "8791"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000002",
                            AccessFailedCount = 0,
                            City = "Gent",
                            ConcurrencyStamp = "d8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maaike@cc.be",
                            EmailConfirmed = true,
                            Firstname = "Maaike",
                            Lastname = "Tubex",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAAIKE@CC.BE",
                            NormalizedUserName = "MAAIKE@CC.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEPhv/khkRqRIEaEXnW4F2aeDs/zWAzdp4e5phNISckqNl9MA8nagKAlPhJbf3y9Ftg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "XVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "maaike@cc.be",
                            Zipcode = "9000"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000003",
                            AccessFailedCount = 0,
                            City = "Waregem",
                            ConcurrencyStamp = "e8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joost@cc.be",
                            EmailConfirmed = true,
                            Firstname = "Joost",
                            Lastname = "Van den Kerkhove",
                            LockoutEnabled = false,
                            NormalizedEmail = "JOOST@CC.BE",
                            NormalizedUserName = "JOOST@CC.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEGEF8pY9md0JAOBZc685NNyDhN0oinmK4ueXhtHwCCNknmodWjgHpBwKt6e/HJ3y6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ZVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "joost@cc.be",
                            Zipcode = "8790"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000004",
                            AccessFailedCount = 0,
                            City = "Harelbeke",
                            ConcurrencyStamp = "e8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "veerle@cc.be",
                            EmailConfirmed = true,
                            Firstname = "Veerle",
                            Lastname = "Hollants",
                            LockoutEnabled = false,
                            NormalizedEmail = "VEERLE@CC.BE",
                            NormalizedUserName = "VEERLE@CC.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEI5CINLtL8SH9mKgiXmTFW5V8XkWCRkPoZWHThBNbZmoa1k/wp3AN+PIk8zHm3BPmQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ZVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "veerle@cc.be",
                            Zipcode = "8530"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000005",
                            AccessFailedCount = 0,
                            City = "Waregem",
                            ConcurrencyStamp = "d8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paulien@cc.be",
                            EmailConfirmed = true,
                            Firstname = "Paulien",
                            Lastname = "Desmet",
                            LockoutEnabled = false,
                            NormalizedEmail = "PAULIEN@CC.BE",
                            NormalizedUserName = "PAULIEN@CC.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAENk4t02iiHpd4MXiaBBDoYlHyjlaRKMUtn6vwEA/XfWDpmk3WUmcyOeBZLGlhRHr8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "XVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "paulien@cc.be",
                            Zipcode = "8790"
                        },
                        new
                        {
                            Id = "00000000-0000-0000-0000-000000000006",
                            AccessFailedCount = 0,
                            City = "Waregem",
                            ConcurrencyStamp = "k8554266-b401-4519-9aeb-a9283053fc58",
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "f.v@telenet.be",
                            EmailConfirmed = true,
                            Firstname = "Filip",
                            Lastname = "Verhelst",
                            LockoutEnabled = false,
                            NormalizedEmail = "F.V@TELENET.BE",
                            NormalizedUserName = "F.V@TELENET.BE",
                            PasswordHash = "AQAAAAEAACcQAAAAEM0Kl8l6aWOoc6YpdBuUe/iDe4GR7YTp/8meOLRvqpmK8f83sofBYr8SpuR2ADECEg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "BVPCRDAS3MJWQD5CSW2GWPRADBXEZINA",
                            TwoFactorEnabled = false,
                            UserName = "f.v@telenet.be",
                            Zipcode = "8790"
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phonenumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jan@desmet.be",
                            Name = "Jan De Smet",
                            Phonenumber = "123/456789"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alex@agnew.be",
                            Name = "Alex Agnew",
                            Phonenumber = "789/456123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "selah@sue.be",
                            Name = "Selah Sue",
                            Phonenumber = "321/654987"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ka@waregem.be",
                            Name = "Stedelijke Kunstacademie Waregem",
                            Phonenumber = "056/123456"
                        },
                        new
                        {
                            Id = 5,
                            Email = "maaike@cc.be",
                            Name = "Eigenproductie-doen",
                            Phonenumber = "056/610061"
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Audiostring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagestring")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("SuccesRate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Videostring")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 2,
                            Description = "Twintig jaar na een spraakmakende affaire bereiden Gracie en haar man Joe zich voor op het afstudeerfeest van hun tweeling. Maar dan komt Hollywood-actrice Elizabeth Berry langs om zich voor te bereiden op haar rol als Gracie in een nieuwe film. Terwijl ze elkaar bestuderen, ontdekken ze dat ze meer overeenkomsten hebben dan ze hadden verwacht.",
                            EventDate = new DateTime(2024, 3, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "may-december.jpg",
                            LocationId = 3,
                            Price = 9.0,
                            SuccesRate = 65,
                            Title = "May December"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            Description = "Ferrari wordt geprezen als een succesverhaal, dankzij hun talloze triomfen in de Formule 1, met iconen zoals Niki Lauda en Michael Schumacher. Oorspronkelijk opgericht in 1929 als raceteam, heeft het Italiaanse automerk echter een hobbelige ontstaansgeschiedenis gekend. In 1957 verkeerde het bedrijf in ernstige financiële problemen, en Ferrari blikt terug op deze uitdagende periode.\r\nDe uitnodigende subtitel van Brock Yates' biografische boek, waar de film op is gebaseerd, leest: 'De man, de auto's, de races en de machine.'",
                            EventDate = new DateTime(2024, 4, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "ferrari.jpg",
                            LocationId = 3,
                            Price = 9.0,
                            SuccesRate = 70,
                            Title = "Ferrari"
                        },
                        new
                        {
                            Id = 3,
                            Audiostring = "Jan De Smet En De Grote Luxe -Mr. Ghost.mp3",
                            CompanyId = 1,
                            Description = "Zanger, muzikant en conservator van het ontroerend muzikaal erfgoed Jan De Smet werd zeventig. In 2024 viert hij die verjaardag met ons in de Schouwburg en het is een Grote Luxe (vandaar de titel!) om hem te mogen ontvangen met een schare uitgelezen muzikanten en zangeressen die een zeer eclectisch muzikaal programma beheersen.",
                            EventDate = new DateTime(2024, 1, 20, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "jan_de_smet_de_grote_luxe.jpg",
                            LocationId = 1,
                            Price = 23.0,
                            SuccesRate = 90,
                            Title = "Jan De Smet en de Grote Luxe",
                            Videostring = "Let's Talk Dirty in Hawaiian-The Bonnie Blues.mp4"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 2,
                            Description = "Alex Agnew geeft in zijn negende comedyshow de post-pandemie-wereld een pandoering",
                            EventDate = new DateTime(2024, 4, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "AA_wake_me_up.jpg",
                            LocationId = 1,
                            Price = 31.0,
                            SuccesRate = 99,
                            Title = "Wake Me Up When It’s Over"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 2,
                            Description = "Na hun succesvolle voorstellingen Mining Stories en Pleasant Island maken Silke Huysmans en Hannes Dereere het sluitstuk van hun trilogie over mijnbouw. Deze keer gaan ze dieper in op een compleet nieuwe industrie: diepzeemijnbouw.",
                            EventDate = new DateTime(2024, 4, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "silke_huysmans_out-of-the-blue.jpg",
                            LocationId = 2,
                            Price = 17.0,
                            SuccesRate = 40,
                            Title = "Out of the Blue "
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 1,
                            Description = "Een actuele situatiekomedie met kleurrijke personages en hilarische toestanden. De Padelburen verzekert het publiek een avond onvervalste pret! Zoals men stilaan gewoon is van Het Prethuis!",
                            EventDate = new DateTime(2024, 5, 28, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "prethuis_de_padelburen.jpg",
                            LocationId = 1,
                            Price = 22.0,
                            SuccesRate = 80,
                            Title = "Het prethuis"
                        },
                        new
                        {
                            Id = 7,
                            Audiostring = "Selah Sue-This World.mp3",
                            CompanyId = 3,
                            Description = "Met festivals gepland in Frankrijk, Spanje, Nederland en Bulgarije, wil Selah Sue helemaal klaar zijn voor haar tour. Dus besluit ze met haar band een tijdje in onze clubzaal te bivakkeren. Tot onze grote vreugde sluit ze die repetitieperiode af met een exclusief try-out concert.",
                            EventDate = new DateTime(2024, 1, 16, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "selah_sue.jpg",
                            LocationId = 2,
                            Price = 35.0,
                            SuccesRate = 100,
                            Title = "Selah Sue (try-out)"
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 4,
                            Description = "De kunstacademie brengt dansen uitgevoerd door de eigen leerlingen.",
                            EventDate = new DateTime(2024, 5, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            LocationId = 1,
                            Price = 5.0,
                            SuccesRate = 75,
                            Title = "Dance 2024"
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 5,
                            Description = "Samen met een professioneel theatermaker van LARF! breng je je wildste toekomstfantasieën tot leven. Je kruipt in de huid van futuristische helden, intergalactische ontdekkingsreizigers en revolutionaire uitvinders. Je onderzoekt wat theater is en ontdekt hoe je zelf speelt en beweegt. Zo ga je op zoek naar je eigen personage met een eigen geluid, hoe luid of stil dat ook is.",
                            EventDate = new DateTime(2024, 7, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Imagestring = "Het theater van de toekomst.jpg",
                            LocationId = 2,
                            Price = 150.0,
                            SuccesRate = 100,
                            Title = "Het theater van de toekomst. Een schakelkamp voor het 4e, 5e en 6e leerjaar"
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Circus"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dans"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Doen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Familie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Humor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Muziek"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Theater"
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 500,
                            Name = "Schouwburg"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 192,
                            Name = "Schakelbox"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 200,
                            Name = "Cinema"
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.NavigationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Navigations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Privacy",
                            Area = "Home",
                            Controller = "Home",
                            Name = "Bescherming",
                            Position = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Area = "Staff",
                            Controller = "Staff",
                            Name = "Voorstellingen",
                            Position = 1
                        },
                        new
                        {
                            Id = 3,
                            Action = "Index",
                            Area = "Staff",
                            Controller = "Company",
                            Name = "Gezelschappen",
                            Position = 2
                        },
                        new
                        {
                            Id = 4,
                            Action = "Index",
                            Area = "Staff",
                            Controller = "Location",
                            Name = "Locaties",
                            Position = 3
                        },
                        new
                        {
                            Id = 5,
                            Action = "NewAbo",
                            Area = "Home",
                            Controller = "Home",
                            Name = "Nieuwe abonee",
                            Position = 2
                        },
                        new
                        {
                            Id = 6,
                            Action = "Voucher",
                            Area = "Home",
                            Controller = "Home",
                            Name = "Waregembon",
                            Position = 3
                        });
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("VisitorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("VisitorId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Quantity = 1,
                            VisitorId = "00000000-0000-0000-0000-000000000006"
                        },
                        new
                        {
                            Id = 2,
                            EventId = 8,
                            Quantity = 1,
                            VisitorId = "00000000-0000-0000-0000-000000000001"
                        });
                });

            modelBuilder.Entity("ApplicationUserEvent", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActionUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventGenre", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Event", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Event", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Company", "Company")
                        .WithMany("Events")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Ticket", b =>
                {
                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", "Visitor")
                        .WithMany("Tickets")
                        .HasForeignKey("VisitorId");

                    b.Navigation("Event");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Company", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Event", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Pri.WebApi.DeSchakel.Core.Entities.Location", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
